# Generated by Django 3.2.25 on 2024-09-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('db_name', models.CharField(max_length=100, verbose_name='이름(SMTC,WEBDB)')),
                ('host', models.CharField(max_length=255, verbose_name='호스트')),
                ('port', models.IntegerField(verbose_name='포트')),
                ('sid', models.CharField(blank=True, max_length=100, null=True, verbose_name='SID/DB명')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자명')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='패스워드')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='추가 옵션')),
                ('backup_bucket', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bucket(Backup) - 미작성 시 자동완성')),
                ('iceberg_bucket', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bucket(Iceberg) - 미작성 시 자동완성')),
            ],
            options={
                'verbose_name': '대상 데이터베이스 리스트',
                'verbose_name_plural': '대상 데이터베이스 리스트',
                'db_table': 'sf_databases',
            },
        ),
        migrations.CreateModel(
            name='LoadInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('interval_type', models.CharField(max_length=100, verbose_name='스케줄 타입')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadinterval_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 로드 주기',
                'verbose_name_plural': '[코드] 로드 주기',
                'db_table': 'sf_load_interval',
            },
        ),
        migrations.CreateModel(
            name='LoadMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('load_type', models.CharField(max_length=100, verbose_name='로드 방법')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadmethod_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 로드 방법',
                'verbose_name_plural': '[코드] 로드 방법',
                'db_table': 'sf_load_method',
            },
        ),
        migrations.CreateModel(
            name='PartitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('partition_type', models.CharField(max_length=100, verbose_name='파티션 타입')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partitiontype_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 파티션 타입',
                'verbose_name_plural': '[코드] 파티션 타입',
                'db_table': 'sf_partition_type',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('use_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='사용 여부')),
                ('table_name', models.CharField(max_length=100, verbose_name='테이블 물리명')),
                ('catalog_db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catalog DB명')),
                ('catalog_table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catalog Table명')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='테이블 논리명')),
                ('cdc_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='CDC 여부')),
                ('sql_where', models.TextField(blank=True, null=True, verbose_name='SQL WHERE 절')),
                ('spark_num_executors', models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Spark : num-executors')),
                ('spark_executor_cores', models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Spark : executor-cores')),
                ('spark_executor_memory', models.BigIntegerField(blank=True, default=4, null=True, verbose_name='Spark : executor-memory(gb)')),
                ('spark_partitionColumn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spark : partitionColumn')),
                ('spark_lowerBound', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spark : lowerBound')),
                ('spark_upperBound', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spark : upperBound')),
                ('spark_numpartitions', models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Spark : numPartitions')),
                ('spark_fetchsize', models.BigIntegerField(blank=True, default=10000, null=True, verbose_name='Spark : fetchsize')),
                ('spark_query', models.TextField(blank=True, null=True, verbose_name='BigTable : Query')),
                ('id_db', models.ForeignKey(blank=True, db_column='id_db', default=7, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.databases', verbose_name='DB명')),
                ('id_load_interval', models.ForeignKey(blank=True, db_column='id_load_interval', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.loadinterval', verbose_name='로드 주기')),
                ('id_load_method', models.ForeignKey(blank=True, db_column='id_load_method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.loadmethod', verbose_name='로드 방법')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tables_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_partition_type', models.ForeignKey(blank=True, db_column='id_partition_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.partitiontype', verbose_name='파티션 타입')),
            ],
            options={
                'verbose_name': '대상 테이블 리스트',
                'verbose_name_plural': '대상 테이블 리스트',
                'db_table': 'sf_tables',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('project_cd', models.CharField(max_length=100, verbose_name='코드명')),
                ('project_name', models.CharField(max_length=100, verbose_name='프로젝트명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 프로젝트',
                'verbose_name_plural': '[코드] 프로젝트',
                'db_table': 'sf_project',
            },
        ),
        migrations.CreateModel(
            name='DbEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('db_env_name', models.CharField(max_length=100, verbose_name='운영/테스트/개발')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dbenv_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 운영/테스트/개발',
                'verbose_name_plural': '[코드] 운영/테스트/개발',
                'db_table': 'sf_db_env',
            },
        ),
        migrations.CreateModel(
            name='DataTypesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('datatype_mapping_name', models.CharField(max_length=50, unique=True, verbose_name='데이터 타입 명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypesmapping_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 매핑 데이터 타입',
                'verbose_name_plural': '[코드] 매핑 데이터 타입',
                'db_table': 'sf_datatypes_mapping',
            },
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('datatype_name', models.CharField(max_length=50, unique=True, verbose_name='데이터 타입 명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypes_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 데이터 타입',
                'verbose_name_plural': '[코드] 데이터 타입',
                'db_table': 'sf_datatypes',
            },
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('db_type_name', models.CharField(max_length=100, unique=True, verbose_name='DB 종류')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databasetype_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[코드] 데이터베이스 종류',
                'verbose_name_plural': '[코드] 데이터베이스 종류',
                'db_table': 'sf_database_types',
            },
        ),
        migrations.AddField(
            model_name='databases',
            name='id_databasetype',
            field=models.ForeignKey(db_column='id_databasetype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.databasetype', verbose_name='DB 종류'),
        ),
        migrations.AddField(
            model_name='databases',
            name='id_dbenv',
            field=models.ForeignKey(db_column='id_dbenv', on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.dbenv', verbose_name='운영/테스트/개발'),
        ),
        migrations.AddField(
            model_name='databases',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databases_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='databases',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartlake.project', verbose_name='프로젝트'),
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('column_name', models.CharField(max_length=100, verbose_name='컬럼 물리명')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='컬럼 논리명')),
                ('use_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='사용 여부')),
                ('pk_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='PK 여부')),
                ('partition_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Partition 여부')),
                ('datatype', models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터 타입')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='columns_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_table', models.ForeignKey(db_column='id_table', on_delete=django.db.models.deletion.CASCADE, to='smartlake.tables', verbose_name='테이블')),
            ],
            options={
                'verbose_name': '대상 컬럼 리스트',
                'verbose_name_plural': '대상 컬럼 리스트',
                'db_table': 'sf_columns',
            },
        ),
    ]
