# Generated by Django 3.2.25 on 2024-09-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlake', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partitiontype',
            table='sl_partition_type',
        ),
    ]
