# Generated by Django 3.2.25 on 2024-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlake', '0002_alter_partitiontype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='columns',
            table='sl_columns',
        ),
        migrations.AlterModelTable(
            name='databases',
            table='sl_databases',
        ),
        migrations.AlterModelTable(
            name='databasetype',
            table='sl_database_types',
        ),
        migrations.AlterModelTable(
            name='datatypes',
            table='sl_datatypes',
        ),
        migrations.AlterModelTable(
            name='datatypesmapping',
            table='sl_datatypes_mapping',
        ),
        migrations.AlterModelTable(
            name='dbenv',
            table='sl_db_env',
        ),
        migrations.AlterModelTable(
            name='loadinterval',
            table='sl_load_interval',
        ),
        migrations.AlterModelTable(
            name='loadmethod',
            table='sl_load_method',
        ),
        migrations.AlterModelTable(
            name='project',
            table='sl_project',
        ),
        migrations.AlterModelTable(
            name='tables',
            table='sl_tables',
        ),
    ]
